#User Configuration

#OE_TERMINAL = "tmux"
IMAGE_INSTALL += " libiio libiio-tests libiio-iiod"
EXTERNALSRC_SYMLINKS:pn-linux-xlnx = ""
# 彻底关闭 Yocto 的时间锁定机制
REPRODUCIBLE_BUILDS = "0"
# 强制不使用 source_date_epoch
BUILD_REPRODUCIBLE_BINARIES = "0"

# 使用全新的强力覆盖语法，强行覆盖所有 distro 发行版默认的 error 配置
SIGGEN_LOCKEDSIGS_CHECK_LEVEL:forcevariable = "warn"
SIGGEN_UNLOCKED_RECIPES:append = " linux-xlnx"
